{% set name = "fisx" %}
{% set version = "1.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 419c9558ef3de2a5bed2b8342ef47d362675cad96d554f9f180c800751cd32d9

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - numpy
    - pip
    - python
    - cython
  run:
    - numpy
    - python

test:
  imports:
    - fisx

about:
  home: https://github.com/vasole/fisx
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Quantitative X-Ray Fluorescence Analysis Support Library
  description: |
    This software library implements formulas to calculate, given an experimental setup, the expected x-ray fluorescence intensities.
    The library accounts for secondary and tertiary excitation, K, L and M shell emission lines and de-excitation cascade effects.
    The basic implementation is written in C++ and a Python binding is provided.

extra:
  recipe-maintainers:
    - tschoonj
